import { initializeApp } from 'firebase/app';
import { 
  getAuth, 
  signInWithEmailAndPassword, 
  createUserWithEmailAndPassword, 
  signInWithPopup, 
  GoogleAuthProvider, 
  signOut, 
  updateProfile,
  sendPasswordResetEmail,
  onAuthStateChanged 
} from 'firebase/auth';
import { 
  getFirestore, 
  collection, 
  doc, 
  getDoc, 
  setDoc, 
  updateDoc, 
  deleteDoc,
  getDocs, 
  query, 
  where, 
  orderBy, 
  limit, 
  onSnapshot,
  increment,
  addDoc,
  serverTimestamp,
  arrayUnion,
  arrayRemove,
  deleteField
} from 'firebase/firestore';
import { 
  getStorage, 
  ref, 
  uploadBytesResumable, 
  getDownloadURL 
} from 'firebase/storage';
import { getFunctions, httpsCallable } from 'firebase/functions';

const firebaseConfig = {
  apiKey: "AIzaSyDjikCtm7RK1CoebQMGQIQTAPh-cC23B-Q",
  authDomain: "pet-maya.firebaseapp.com",
  projectId: "pet-maya",
  storageBucket: "pet-maya.firebasestorage.app",
  messagingSenderId: "335402911476",
  appId: "1:335402911476:web:841262770bb408768a00a1",
  measurementId: "G-WSN2ZQE4PF"
};

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);
export const functions = getFunctions(app, 'us-central1');
export const googleProvider = new GoogleAuthProvider();

export {
  httpsCallable,
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  signInWithPopup,
  signOut,
  updateProfile,
  sendPasswordResetEmail,
  onAuthStateChanged,
  collection,
  doc,
  getDoc,
  setDoc,
  updateDoc,
  deleteDoc,
  getDocs,
  query,
  where,
  orderBy,
  limit,
  onSnapshot,
  increment,
  addDoc,
  serverTimestamp,
  arrayUnion,
  arrayRemove,
  deleteField,
  ref,
  uploadBytesResumable,
  getDownloadURL
};

// ── INITIAL SEED DATA FOR DEMO & INSTANT RENDERING ──
export const INITIAL_PETS = [
  { id: 'pet-1', name: 'Max', species: 'Dog', breed: 'Golden Retriever', gender: 'Male', age: '3 Yrs', weight: '28.4 kg', photo: 'assets/images/Pet_1.jpg', microchip: 'PM-99482-GOLD', nextVaccine: '2026-09-15' },
  { id: 'pet-2', name: 'Luna', species: 'Cat', breed: 'British Shorthair', gender: 'Female', age: '2 Yrs', weight: '4.2 kg', photo: 'assets/images/Pet_2.jpg', microchip: 'PM-11823-BRIT', nextVaccine: '2026-10-02' }
];

export const INITIAL_VETS = [
  { id: 'v1', name: 'Dr. Sarah Jenkins', qualification: 'DVM, MRCVS • Small Animal Surgery', tag: 'Veterinarian', rating: 4.9, reviewsCount: 68, distance: '1.2 km away', price: '৳35/visit', availability: 'Mon - Fri • 9am - 6pm', verified: true, isVerified: true, bio: '12+ years clinical experience in orthopedics, emergency soft tissue surgery, and canine preventative care.', photo: 'assets/images/Pet_1.jpg', clinic: 'Greenwood Animal Hospital' },
  { id: 'v2', name: 'Dr. Aris Thorne', qualification: 'BVSc, PhD • Feline Medicine & Dermatology', tag: 'Veterinarian', rating: 5.0, reviewsCount: 42, distance: '2.8 km away', price: '৳45/visit', availability: 'Tue - Sat • 10am - 7pm', verified: true, isVerified: true, bio: 'Specialist in feline chronic kidney disease, allergic dermatitis, and clinical cytology diagnostics.', photo: 'assets/images/Pet_2.jpg', clinic: 'Metropolitan Veterinary Center' },
  { id: 'v3', name: 'Dr. Emily Vance', qualification: 'DVM • Internal Medicine & Cardiology', tag: 'Veterinarian', rating: 4.8, reviewsCount: 51, distance: '3.5 km away', price: '৳40/visit', availability: 'Daily • 8am - 4pm', verified: true, isVerified: true, bio: 'Expert in echocardiography, metabolic triage, and comprehensive canine/feline cardiac disease management.', photo: 'assets/images/Pet_1.jpg', clinic: 'City Vets & Diagnostics' },
  { id: 'v4', name: 'Pawfect Spa & Grooming', qualification: 'Master Groomer Certified • Hydrobath & Styling', tag: 'Grooming Spa', rating: 4.9, reviewsCount: 89, distance: '0.8 km away', price: '৳25/session', availability: 'Mon - Sun • 9am - 8pm', verified: true, isVerified: true, bio: 'Deluxe stress-free grooming, flea & tick therapeutic baths, and precision breed styling.', photo: 'assets/images/Pet_2.jpg', clinic: 'Pawfect Pet Wellness Studio' },
  { id: 'v5', name: 'Happy Tails Luxury Boarding', qualification: '24/7 Monitored Pet Hotel & Agility Park', tag: 'Boarding Resort', rating: 4.9, reviewsCount: 112, distance: '4.1 km away', price: '৳30/night', availability: '24/7 Check-in', verified: true, isVerified: true, bio: 'Climate-controlled suites, live webcams, individualized playtime, and on-call veterinary supervision.', photo: 'assets/images/Pet_1.jpg', clinic: 'Happy Tails Resort' },
  { id: 'v6', name: 'Apex Pet Supplies & Pharmacy', qualification: 'Licensed Veterinary Pharmacy & Specialty Diet Depot', tag: 'Pet Shop', rating: 4.8, reviewsCount: 94, distance: '1.5 km away', price: 'Free Delivery', availability: 'Daily • 8am - 10pm', verified: true, isVerified: true, bio: 'Prescription veterinary diets, authentic tick/flea preventatives, supplements, and premium accessories.', photo: 'assets/images/Pet_2.jpg', clinic: 'Apex Pet Hub' }
];

export const INITIAL_PRODUCTS = [
  {
    id: 'p1',
    name: 'Royal Canin Golden Retriever Adult',
    category: 'food',
    price: 64.99,
    originalPrice: 79.99,
    discountPct: 19,
    name: 'NexGard Spectra Chews',
    brand: 'BOEHRINGER INGELHEIM',
    category: 'canine_rx',
    categoryLabel: 'Canine Rx',
    badge: 'CANINE RX',
    rating: 4.9,
    ratingCount: 128,
    stock: 24,
    brand: 'Royal Canin',
    badge: 'BEST SELLER',
    sku: 'RC-GR-3KG',
    ratingCount: 184,
    subtag: 'Annual Doses • Chewable',
    description: 'Monthly chewable broad-spectrum protection against fleas, ticks, heartworms, and intestinal roundworms & hookworms.',
    price: 1650,
    isRx: true,
    ctaText: '+ Quick Add',
    stock: 28,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyyaRDTb2W0SyWzpotHdYAApqW2ydxhtGyeEKl6loLi_sYPbDWkdK5abfVRN9IKB4VURTDfr4KM87oTm4tTleP5tpUVnjtMaFBhPdmHM5VsoerwkyzFt0iGGLkM92fmTpK6cSKeAtoffqDf8pMSx5UIR2kr0CXLUKEcWxhdQNDi6xwl6s-upiyklCSkWtQom61laln9mF-vojFZAeX8erkCObUVa0YkuH810Jx9alUj5Y2EBk1q8y5'
  },
  {
    id: 'p2',
    name: 'Royal Canin Gastro Low Fat',
    brand: 'VETERINARY FORMULATIONS',
    category: 'clinical_diets',
    categoryLabel: 'Clinical Diets',
    badge: 'CLINICAL DIET',
    rating: 4.8,
    ratingCount: 92,
    subtag: 'Microbiome Support • 6kg',
    description: 'Prescription diet formula tailored for dogs with hyperlipidemia, acute pancreatitis, and severe fat digestive disorders.',
    price: 3450,
    isRx: false,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&auto=format&fit=crop&q=80',
    description: 'Tailored kibble designed specifically for the cardiac health and coat barrier of adult Golden Retrievers.',
    specifications: {
      weight: '3.0 kg',
      lifestage: 'Adult (Over 15 months)',
      breedSuitability: 'Golden Retriever & large retriever breeds',
      origin: 'France (Imported)'
    },
    usageGuide: 'Feed 330g - 380g daily divided into 2 meals based on activity level. Fresh water must always be available.'
    ctaText: '+ Quick Add',
    stock: 15,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9U3FvzjziZczps6X5sPuuKuOX40qPLobWacnfI85tXLCZynTpweICAvn1dLwFc9T5lqog-bfsF38U9Dym32m7PzER89u92kYfrWQZMXJVhsSwuSAYglUNVMBtRSS_UPDx21dAcpP859PySdRyKwRCayRXp0_C6n0msFfQiMHQ4NavEuLEEtANuQeqX6v63iNpa9j2pOz8oP7OznX_dJp2msH0v7vP4bj-QRFW8ZLuf_lel-VHhL0L'
  },
  {
    id: 'p2',
    name: 'Simparica Trio Chewables (3-Pack)',
    category: 'pharma',
    price: 42.50,
    originalPrice: 49.99,
    discountPct: 15,
    id: 'p3',
    name: 'Nobivac Rabies Biologic',
    brand: 'MSD ANIMAL HEALTH',
    category: 'cold_chain',
    categoryLabel: 'Cold-Chain Biologics',
    badge: '2°C - 8°C REFRIGERATED',
    badgeType: 'cold',
    tagRight: 'VIAL 1M',
    rating: 5.0,
    ratingCount: 240,
    subtag: 'Cold-Chain Monitored • Vaccine',
    description: 'Inactivated rabies antigen formulation for proactive immunization. Transported in hermetic cold-chain vacuum pods.',
    price: 850,
    isRx: true,
    ctaText: '❄️ Reserve Rx',
    stock: 45,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCl5hQZ6ayu5ehyl5fSHlkzD2Mfci7ba4G5q4HZbE6yHowWAuV0pLdSTsGsvDQSjSQG1X76gwnYLJk3Ojlx7jPKLE5GOWy31Z0bYwwMHrwhqCQiPqGjU2WORBhZB_7wXYga5YQgph5DnjXRDVrhapnWE-Ko5xCvXt0UX9m0N7qFFiQzIG-VWAEZKH33hGIJZ_PDZPYWVyv-hXWuwXNcldIw0YakHmMrkSdcx9tUP3i87_EOQM-qKbsU'
  },
  {
    id: 'p4',
    name: 'Synoquin EFA Joint Care',
    brand: 'VETPLUS UK',
    category: 'joint_mobility',
    categoryLabel: 'Joint & Mobility',
    badge: 'JOINT THERAPEUTICS',
    rating: 4.9,
    ratingCount: 67,
    subtag: 'DEXAHAN • 90 CAPS',
    description: 'High purity glucosamine HCl, chondroitin sulphate, and bioactive Dexahan for joint cartilage nourishment and agility.',
    price: 2100,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 22,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAtnwsm_JiwhU3Ov-f5bQDXY-4k8fGBLuVf7PSzSjR4M3p6D32krDyyQplZFL0O3qGzaXhazXOi84U-lYKxymoS2pLtaszYPb5w-tlmgWY0FE432Btn5Dl7qVgXk7bkuem38s2Ow4xx35YI_VHtZd4fNB1YPq2HjNyiORfxzRLPHiWO6wEl9WrucZHItG-glHVv0jKeJ165nrNmdQrnN1XJ_pkpAiaKPaezgoIcAUk0SCcf6P2AoR0A'
  },
  {
    id: 'p5',
    name: 'Apoquel 16mg Oclacitinib',
    brand: 'ZOETIS ANIMAL HEALTH',
    category: 'canine_rx',
    categoryLabel: 'Canine Rx',
    badge: 'PRESCRIPTION CONTROLLED',
    tagRight: '30 VEGET-CAPS',
    rating: 4.9,
    ratingCount: 153,
    subtag: 'JAK1 INHIBITOR • 16 MG',
    description: 'Targeted kinase inhibition for immediate control of pruritus associated with canine allergic and atopic dermatitis.',
    price: 4200,
    isRx: true,
    ctaText: '📋 Submit Rx',
    stock: 19,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p6',
    name: 'Feliway Optimum Starter',
    brand: 'CEVA SANTE ANIMALE',
    category: 'feline_care',
    categoryLabel: 'Feline Care',
    badge: 'FELINE BEHAVIORAL',
    rating: 4.7,
    ratingCount: 119,
    subtag: 'Advanced Pheromone • 30 DAYS',
    description: 'New feline pheromone complex calming holistic reassurance to prevent scratching, urine spraying, and multi-cat tension.',
    price: 3100,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 18,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p7',
    name: 'Bravecto Chewable Dog (20–40kg)',
    brand: 'MSD ANIMAL HEALTH',
    category: 'canine_rx',
    categoryLabel: 'Canine Rx',
    badge: 'CANINE RX',
    rating: 4.9,
    ratingCount: 142,
    subtag: 'Fluralaner • 3 MONTHS',
    description: 'Extended 12-week systemic chewable protection against fleas and ticks for large dogs.',
    price: 2850,
    isRx: true,
    ctaText: '+ Quick Add',
    stock: 16,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p8',
    name: 'Hills Prescription Diet i/d Digestive',
    brand: 'HILLS PET NUTRITION',
    category: 'clinical_diets',
    categoryLabel: 'Clinical Diets',
    badge: 'CLINICAL DIET',
    rating: 4.8,
    ratingCount: 78,
    subtag: 'Prebiotic ActivBiome+ • 5kg',
    description: 'Highly digestible nutrition clinically proven to settle digestive upsets and nourish the gut microbiome.',
    price: 3650,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 12,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p9',
    name: 'Vanguard Plus 5 L4 CV Biologic',
    brand: 'ZOETIS ANIMAL HEALTH',
    category: 'cold_chain',
    categoryLabel: 'Cold-Chain Biologics',
    badge: '2°C - 8°C REFRIGERATED',
    badgeType: 'cold',
    tagRight: '1 DOSE',
    rating: 4.9,
    ratingCount: 112,
    subtag: 'Cold-Chain Monitored • DHPPi',
    description: 'Comprehensive canine immunization protecting against canine distemper, adenovirus, parvo, and leptospirosis.',
    price: 980,
    isRx: true,
    ctaText: '❄️ Reserve Rx',
    stock: 30,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p10',
    name: 'Cosequin DS Plus MSM Chewables',
    brand: 'NUTRAMAX LABS',
    category: 'joint_mobility',
    categoryLabel: 'Joint & Mobility',
    badge: 'JOINT THERAPEUTICS',
    rating: 4.9,
    ratingCount: 89,
    subtag: 'Glucosamine/Chondroitin • 132 TABS',
    description: 'Double strength joint health supplement with MSM to support mobility, cartilage matrix, and daily comfort.',
    price: 2450,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 14,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p11',
    name: 'Revolution Plus for Cats (2.5–5kg)',
    brand: 'ZOETIS ANIMAL HEALTH',
    category: 'feline_care',
    categoryLabel: 'Feline Care',
    badge: 'FELINE CARE',
    rating: 4.8,
    ratingCount: 96,
    subtag: 'Selamectin/Sarolaner • 3 PIPETTES',
    description: 'Broadest spectrum 6-in-1 topical parasite defense protecting against fleas, ticks, ear mites, and heartworms.',
    price: 1750,
    isRx: true,
    ctaText: '+ Quick Add',
    stock: 20,
    image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p12',
    name: 'Felocell 4 Feline Core Vaccine',
    brand: 'ZOETIS ANIMAL HEALTH',
    category: 'cold_chain',
    categoryLabel: 'Cold-Chain Biologics',
    badge: '2°C - 8°C REFRIGERATED',
    badgeType: 'cold',
    tagRight: '1 DOSE',
    rating: 5.0,
    ratingCount: 104,
    subtag: 'Cold-Chain Vault • FVRCP',
    description: 'Vaccination of healthy cats against feline rhinotracheitis, calicivirus, panleukopenia, and Chlamydia psittaci.',
    price: 920,
    isRx: true,
    ctaText: '❄️ Reserve Rx',
    stock: 35,
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p13',
    name: 'Royal Canin Renal Support Feline',
    brand: 'VETERINARY FORMULATIONS',
    category: 'clinical_diets',
    categoryLabel: 'Clinical Diets',
    badge: 'CLINICAL DIET',
    rating: 4.9,
    ratingCount: 63,
    subtag: 'Low Phosphorus • 2kg',
    description: 'Precision veterinary diet formulated with adapted protein and restricted phosphorus for feline kidney function.',
    price: 3200,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 10,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p14',
    name: 'Simparica Trio Purple Chewables',
    brand: 'ZOETIS ANIMAL HEALTH',
    category: 'canine_rx',
    categoryLabel: 'Canine Rx',
    badge: 'CANINE RX',
    rating: 5.0,
    ratingCount: 215,
    subtag: 'Monthly Chewable • 3 PACK',
    description: 'Convenient monthly triple defense protecting dogs against 5 species of ticks, fleas, and heartworm disease.',
    price: 1950,
    isRx: true,
    ctaText: '+ Quick Add',
    stock: 25,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p15',
    name: 'Feliway Classic Refill Vials',
    brand: 'CEVA SANTE ANIMALE',
    category: 'feline_care',
    categoryLabel: 'Feline Care',
    badge: 'FELINE BEHAVIORAL',
    rating: 4.7,
    ratingCount: 84,
    subtag: 'Facial Pheromone • 48ML',
    description: 'Bio-identical feline facial pheromone refill for continuous ambient security and stress reduction in home environments.',
    price: 2200,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 14,
    brand: 'Zoetis Rx',
    badge: 'VET APPROVED',
    sku: 'SIM-TRIO-MED',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p16',
    name: 'Adequan Canine Polysulfated GAG',
    brand: 'AMERICAN REGENT',
    category: 'joint_mobility',
    categoryLabel: 'Joint & Mobility',
    badge: 'JOINT THERAPEUTICS',
    rating: 4.9,
    ratingCount: 45,
    subtag: 'Injectable Glycosaminoglycan',
    description: 'Disease-modifying osteoarthritis formulation that inhibits cartilage breakdown and stimulates synovial hyaluronic acid.',
    price: 4800,
    isRx: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'All-in-one monthly chewable protection against fleas, ticks, heartworm disease, roundworms, and hookworms.',
    specifications: {
      dosage: '1 chewable tablet monthly',
      weightRange: '10kg – 20kg (22 – 44 lbs)',
      storage: 'Room temperature (20°C - 25°C)',
      activeIngredients: 'Sarolaner, Moxidectin, Pyrantel'
    },
    usageGuide: 'Administer orally once monthly with or without food. Ensure pet consumes full dose for complete protection.'
    ctaText: '📋 Submit Rx',
    stock: 8,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p3',
    name: 'Smart GPS & Health Collar V3',
    category: 'tech',
    price: 89.00,
    originalPrice: 119.00,
    discountPct: 25,
    id: 'p17',
    name: 'Purina Pro Plan HA Hydrolyzed Canine',
    brand: 'PURINA VETERINARY DIETS',
    category: 'clinical_diets',
    categoryLabel: 'Clinical Diets',
    badge: 'CLINICAL DIET',
    rating: 4.8,
    ratingCount: 52,
    subtag: 'Hypoallergenic • 3kg',
    description: 'Hydrolyzed soy protein formulation designed to avoid adverse food reactions in highly sensitive canine patients.',
    price: 3900,
    isRx: false,
    ctaText: '+ Quick Add',
    stock: 11,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p18',
    name: 'Nobivac Tricat Trio Biologic',
    brand: 'MSD ANIMAL HEALTH',
    category: 'cold_chain',
    categoryLabel: 'Cold-Chain Biologics',
    badge: '2°C - 8°C REFRIGERATED',
    badgeType: 'cold',
    tagRight: '1 DOSE',
    rating: 4.9,
    ratingCount: 76,
    stock: 9,
    brand: 'Pet Maya Tech',
    badge: 'NEW HARDWARE',
    sku: 'PM-COLLAR-V3',
    subtag: 'Cold-Chain Monitored • Feline',
    description: 'Attenuated live vaccine against feline calicivirus, herpesvirus type 1, and feline panleukopenia virus.',
    price: 890,
    isRx: true,
    ctaText: '❄️ Reserve Rx',
    stock: 28,
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p19',
    name: 'Credelio Lotilaner Chewable Tablets',
    brand: 'ELANCO ANIMAL HEALTH',
    category: 'canine_rx',
    categoryLabel: 'Canine Rx',
    badge: 'CANINE RX',
    rating: 4.8,
    ratingCount: 61,
    subtag: 'Tick & Flea Defense • 3 CHEWS',
    description: 'Pure extra-purified lotilaner providing rapid flea elimination within 4 hours and sustained 30-day efficacy.',
    price: 1800,
    isRx: true,
    ctaText: '+ Quick Add',
    stock: 16,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p20',
    name: 'Profender Feline Topical Dewormer',
    brand: 'ELANCO ANIMAL HEALTH',
    category: 'feline_care',
    categoryLabel: 'Feline Care',
    badge: 'FELINE CARE',
    rating: 4.8,
    ratingCount: 73,
    subtag: 'Emodepside/Praziquantel',
    description: 'Stress-free spot-on anthelmintic targeting gastrointestinal roundworms, hookworms, and tapeworms in domestic cats.',
    price: 1450,
    isRx: false,
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&auto=format&fit=crop&q=80',
    description: 'Real-time cellular GPS tracking, geofence escape alarms, activity telemetry, and sound buzzer collar.',
    specifications: {
      connectivity: '4G LTE-M / NB-IoT / BLE 5.2 / GNSS',
      batteryLife: 'Up to 14 days on smart standby',
      waterproof: 'IP68 certified submersible',
      weight: '32 grams lightweight ergonomic'
    },
    usageGuide: 'Pair via Bluetooth with Pet Maya app in under 60 seconds. Set safe zones around home perimeter.'
    ctaText: '+ Quick Add',
    stock: 22,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p4',
    name: 'Purina Pro Plan LiveClear Cat Food',
    category: 'food',
    price: 48.99,
    originalPrice: 58.00,
    discountPct: 16,
    id: 'p21',
    name: 'Royal Canin Urinary S/O Moderate Calorie',
    brand: 'VETERINARY FORMULATIONS',
    category: 'clinical_diets',
    categoryLabel: 'Clinical Diets',
    badge: 'CLINICAL DIET',
    rating: 4.9,
    ratingCount: 88,
    stock: 18,
    brand: 'Purina Pro Plan',
    badge: 'ALLERGEN REDUCING',
    sku: 'PUR-LC-CAT-15',
    ratingCount: 110,
    subtag: 'Struvite Dissolution • 3.5kg',
    description: 'Formulated to dissolve struvite uroliths and prevent recurrence while moderating calorie intake.',
    price: 3550,
    isRx: false,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&auto=format&fit=crop&q=80',
    description: 'Revolutionary feline nutrition that safely neutralizes Fel d 1 allergen in cat saliva and dander.',
    specifications: {
      weight: '1.5 kg',
      primaryProtein: 'Real Turkey & Rice',
      target: 'Adult cats in multi-human allergen-sensitive households',
      allergenReduction: 'Average 47% reduction starting week 3'
    },
    usageGuide: 'Feed daily as sole diet for maximum allergen reduction effect. Transition gradually over 7–10 days.'
    ctaText: '+ Quick Add',
    stock: 14,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p5',
    name: 'Orthopedic Memory Foam Pet Bed',
    category: 'supplies',
    price: 54.00,
    originalPrice: 68.00,
    discountPct: 20,
    rating: 4.7,
    ratingCount: 92,
    id: 'p22',
    name: 'Antisedan & Dexdomitor Reversal Kit',
    brand: 'ORION PHARMA',
    category: 'canine_rx',
    categoryLabel: 'Canine Rx',
    badge: 'PRESCRIPTION CONTROLLED',
    tagRight: '10ML VIAL',
    rating: 5.0,
    ratingCount: 31,
    subtag: 'Atipamezole HCl • 10ml',
    description: 'Selective alpha-2 adrenergic receptor antagonist for clinical sedation reversal and physiological recovery.',
    price: 3800,
    isRx: true,
    ctaText: '📋 Submit Rx',
    stock: 6,
    brand: 'FurHaven Ergonomics',
    badge: 'COMFORT CHOICE',
    sku: 'BED-ORTHO-XL',
    isRx: false,
    image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=500&auto=format&fit=crop&q=80',
    description: 'High-density memory foam base with waterproof lining designed for joint relief and deep recovery sleep.',
    specifications: {
      dimensions: '90cm x 70cm x 15cm (Large/XL)',
      foamDensity: 'Medical grade 4-inch memory slab',
      cover: 'Removable machine-washable plush microsuede',
      base: 'Non-skid silicone dotted underside'
    },
    usageGuide: 'Allow 24 hours for memory foam core to fully expand upon unboxing before first pet use.'
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p6',
    name: 'Otomax Clinical Ear Drops (15g)',
    category: 'pharma',
    price: 28.00,
    originalPrice: 34.50,
    discountPct: 18,
    rating: 4.9,
    ratingCount: 64,
    stock: 12,
    brand: 'Merck Animal Health',
    badge: 'PRESCRIPTION RX',
    sku: 'OTO-CLIN-15G',
    id: 'p23',
    name: 'Canidryl 50mg Carprofen NSAID',
    brand: 'CHANELLE PHARMA',
    category: 'joint_mobility',
    categoryLabel: 'Joint & Mobility',
    badge: 'JOINT THERAPEUTICS',
    rating: 4.7,
    ratingCount: 59,
    subtag: 'Anti-inflammatory • 20 TABS',
    description: 'Palatable non-steroidal anti-inflammatory tablet for relief of perioperative pain and chronic musculoskeletal inflammation.',
    price: 1600,
    isRx: true,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
    description: 'Veterinary prescription anti-inflammatory, antifungal, and antibacterial suspension for canine otitis.',
    specifications: {
      volume: '15g dropper tube',
      formula: 'Gentamicin, Betamethasone, Clotrimazole',
      storage: 'Keep refrigerated (2°C – 8°C)',
      coldChainDelivery: 'Shipped in insulated cold pack'
    },
    usageGuide: 'Instill 4 drops into affected ear canal twice daily for 7 days or as directed by attending veterinarian.'
    ctaText: '📋 Submit Rx',
    stock: 17,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'p24',
    name: 'Purevax Feline Rabies Biologic',
    brand: 'BOEHRINGER INGELHEIM',
    category: 'cold_chain',
    categoryLabel: 'Cold-Chain Biologics',
    badge: '2°C - 8°C REFRIGERATED',
    badgeType: 'cold',
    tagRight: '1 DOSE',
    rating: 5.0,
    ratingCount: 92,
    subtag: 'Canarypox Vector • Vaccine',
    description: 'Non-adjuvanted canarypox recombinant rabies biologic formulated to eliminate local injection-site chronic inflammation.',
    price: 1250,
    isRx: true,
    ctaText: '❄️ Reserve Rx',
    stock: 40,
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80'
  }
];

export const INITIAL_POSTS = [
  {
    id: 'post-1',
    author: 'Alex Johnson',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    petTag: 'Max (Golden Retriever)',
    timestamp: '2 hours ago',
    content: 'Max completed his agility championship sprint today! Huge shoutout to Dr. Sarah Jenkins for his joint health routine. 🐾🏅',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&auto=format&fit=crop&q=80',
    likes: 24,
    likedByMe: false,
    comments: [
      { author: 'Dr. Sarah Jenkins', text: 'So proud of Max! Keep up the daily joint mobility exercises!' }
    ]
  },
  {
    id: 'post-2',
    author: 'Elena Vance',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    petTag: 'Luna (British Shorthair)',
    timestamp: '5 hours ago',
    content: 'Just tried the AI Health Diagnostic scanner for Luna’s tear staining. Super detailed first aid advice before our vet visit! ✨',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    likes: 19,
    likedByMe: false,
    comments: []
  },
  {
    id: 'post-3',
    author: 'Rahim Chowdhury',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    petTag: 'Bruno (Golden Retriever)',
    category: 'Lost & Found',
    timestamp: '45 mins ago',
    content: '🚨 LOST PET ALERT: Bruno slipped his leash near Gulshan Lake Park! He is wearing an orange collar with PetMaya BLE Tag (PM-BLE-4109). Microchip #BD-982-004-912. Very friendly. Please call +880 1712-345678 if sighted! 🙏🐾',
    image: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=600&auto=format&fit=crop&q=80',
    isAmberAlert: true,
    isResolved: false,
    petName: 'Bruno',
    petBreed: 'Golden Retriever, 3 Yrs',
    location: 'Gulshan Lake Park, Dhaka',
    contactPhone: '+880 1712-345678',
    microchipId: 'BD-982-004-912',
    collarTag: 'PM-BLE-4109',
    reward: '৳ 5,000',
    likes: 42,
    likedByMe: false,
    comments: [
      { author: 'Dr. Sarah Jenkins', text: 'Alert sent to nearby clinic networks in Gulshan & Banani! Hope Bruno is safely home soon.' }
    ]
  }
];
