// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjikCtm7RK1CoebQMGQIQTAPh-cC23B-Q',
    appId: '1:335402911476:web:841262770bb408768a00a1',
    messagingSenderId: '335402911476',
    projectId: 'pet-maya',
    authDomain: 'pet-maya.firebaseapp.com',
    storageBucket: 'pet-maya.firebasestorage.app',
    measurementId: 'G-WSN2ZQE4PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHG50yAF3WgkJ4xvUdwjglr9gdkgRulqs',
    appId: '1:335402911476:android:a4eed64c2643f4ee8a00a1',
    messagingSenderId: '335402911476',
    projectId: 'pet-maya',
    storageBucket: 'pet-maya.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKyE5Trv_7BYjYbn_xz2vwTHSHv8pBkLo',
    appId: '1:335402911476:ios:78b00e154e08bfb78a00a1',
    messagingSenderId: '335402911476',
    projectId: 'pet-maya',
    storageBucket: 'pet-maya.firebasestorage.app',
    iosClientId: '335402911476-q0ibcv1sfoli6tg8l9j63ghp9iq71bfj.apps.googleusercontent.com',
    iosBundleId: 'com.vertexhand.petmaya',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKyE5Trv_7BYjYbn_xz2vwTHSHv8pBkLo',
    appId: '1:335402911476:ios:552a3228a7bb52a48a00a1',
    messagingSenderId: '335402911476',
    projectId: 'pet-maya',
    storageBucket: 'pet-maya.firebasestorage.app',
    iosClientId: '335402911476-d7ptqq8jms40agfpbl9nj98s31v1e248.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailwagging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjikCtm7RK1CoebQMGQIQTAPh-cC23B-Q',
    appId: '1:335402911476:web:56fce0c7bcc55fab8a00a1',
    messagingSenderId: '335402911476',
    projectId: 'pet-maya',
    authDomain: 'pet-maya.firebaseapp.com',
    storageBucket: 'pet-maya.firebasestorage.app',
    measurementId: 'G-R1CTMQD8MV',
  );
}
