// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiWWmH0hlPlgnlyMiaNr5fRiINlGIwH8',
    appId: '1:849611779485:web:d9b32684c418bdd663d374',
    messagingSenderId: '849611779485',
    projectId: 'tail-wagging-d03de',
    authDomain: 'tail-wagging-d03de.firebaseapp.com',
    databaseURL: 'https://tail-wagging-d03de-default-rtdb.firebaseio.com',
    storageBucket: 'tail-wagging-d03de.firebasestorage.app',
    measurementId: 'G-5C0WFRBQG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6h140AXRy-jf2juyuN7sa6X4PqkYx62I',
    appId: '1:849611779485:android:49b51a70e129b09463d374',
    messagingSenderId: '849611779485',
    projectId: 'tail-wagging-d03de',
    databaseURL: 'https://tail-wagging-d03de-default-rtdb.firebaseio.com',
    storageBucket: 'tail-wagging-d03de.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpIkTyfwR7KxFaxxDnEnNRgdLTPrZ3usM',
    appId: '1:849611779485:ios:b759750e569364d463d374',
    messagingSenderId: '849611779485',
    projectId: 'tail-wagging-d03de',
    databaseURL: 'https://tail-wagging-d03de-default-rtdb.firebaseio.com',
    storageBucket: 'tail-wagging-d03de.firebasestorage.app',
    androidClientId: '849611779485-05khsm7dbr8rq7f0r47neotb9vcd9oh2.apps.googleusercontent.com',
    iosClientId: '849611779485-7vkllj0ceu0nmmatb1cmnemn3sijons4.apps.googleusercontent.com',
    iosBundleId: 'com.vertexhand.petmaya',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpIkTyfwR7KxFaxxDnEnNRgdLTPrZ3usM',
    appId: '1:849611779485:ios:9f075cdc317d251963d374',
    messagingSenderId: '849611779485',
    projectId: 'tail-wagging-d03de',
    databaseURL: 'https://tail-wagging-d03de-default-rtdb.firebaseio.com',
    storageBucket: 'tail-wagging-d03de.firebasestorage.app',
    androidClientId: '849611779485-05khsm7dbr8rq7f0r47neotb9vcd9oh2.apps.googleusercontent.com',
    iosClientId: '849611779485-dfptvu3bv2iv29nh5n0ppad2m6idag5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailwagging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmiWWmH0hlPlgnlyMiaNr5fRiINlGIwH8',
    appId: '1:849611779485:web:ec01672490c4f33263d374',
    messagingSenderId: '849611779485',
    projectId: 'tail-wagging-d03de',
    authDomain: 'tail-wagging-d03de.firebaseapp.com',
    databaseURL: 'https://tail-wagging-d03de-default-rtdb.firebaseio.com',
    storageBucket: 'tail-wagging-d03de.firebasestorage.app',
    measurementId: 'G-6X2EVVNLQJ',
  );
}
